### ISSUE TITLE
"Plugin didn't set meta_result" (but it did)

### ISSUE THREAD

**Issue by wootguy** [hzqst/metamod-fallguys#7]
I'm getting this warning for some plugins, even when the meta result is set. The plugin it complains about can change depending on which plugins are loaded.

It happens most reliably from this [Mute plugin](https://github.com/wootguy/Mute/blob/master/src/main.cpp#L181). As soon as I join the server the console is flooded with `[META] WARNING: Plugin didn't set meta_result: Mute.so:Voice_SetClientListening()`. I think it's only happening on linux dedicated. I'm using your build of metamod+plugins.

plugins.ini:
```
linux addons/metamod/dlls/ascurl.so
linux addons/metamod/dlls/asqcvar.so
linux addons/metamod/dlls/asusermsg.so
linux addons/metamod/dlls/fallguys.so

linux addons/metamod/dlls/Mute.so
```

[mute_libs.zip](https://github.com/hzqst/metamod-fallguys/files/10820660/mute_files.zip)

**Comment by hzqst** [comment]
It seems that `Voice_SetClientListening` (https://github.com/wootguy/Mute/blob/427a01225f42c88b5eafcf53e250bd046c608313/src/main.cpp#L174) never got called by metamod until I renamed `Voice_SetClientListening` to something like `NewVoice_SetClientListening` or `Voice_SetClientListening2333333`

So it could be an issue with symbol confliction from dlsym or what.

**Comment by wootguy** [comment]
Yeah that's weird. The warning goes away when renaming the function or making it static. I'll try to figure out what metamod change caused that.

**Comment by wootguy** [comment]
Removing [this code](https://github.com/hzqst/metamod-fallguys/blob/00b4b25425d1d3e4f8bb2f0432e5b3505d83d934/metamod/engineinfo.cpp#L247-L250) fixes the conflict but also breaks the fallguys plugins. I have no idea what I'm looking at now so I'm giving up on figuring out why this happens. I'll just rename my hook functions.
