### ISSUE TITLE
High CPU usage from fallguys.so on all maps

### ISSUE THREAD

**Issue by wootguy** [hzqst/metamod-fallguys#8]
Some fallguys.so code is running on all maps.

![image](https://user-images.githubusercontent.com/12087544/221094920-fd9a42b0-6b66-4908-972b-dfbc9e85baf3.png)
The server is empty right now, but fallguys.so was around 10% earlier with more players.

The 1st table is CPU time spent across all game libs.
The 2nd table is CPU time spent in fallguys.so.

**Comment by hzqst** [comment]
Probably need an API to enable/disable physic world globally.

**Comment by wootguy** [comment]
That fixed it.

abandoned.bsp (before)
![image](https://user-images.githubusercontent.com/12087544/221264826-c0436bdc-f6fa-47ce-8f08-8400dbc314ec.png)

abandoned.bsp (after)
![image](https://user-images.githubusercontent.com/12087544/221264932-9d520dd0-2fdc-42b1-a0d9-eace14436a55.png)
